@baseUrl = http://localhost:8080

### Info
GET {{baseUrl}}/info

### Health Check
GET {{baseUrl}}/health

### Create a new wish for user1
POST {{baseUrl}}/wishes/user1
Content-Type: application/json

{
    "title": "Learn Python",
    "wishId": "wish1",
    "content": "Work through Python tutorials and build a project.",
    "priority": 4,
    "due": "2024-06-01T00:00:00Z"
}

### Create another wish for user1
POST {{baseUrl}}/wishes/user1
Content-Type: application/json

{
    "title": "Learn Go",
    "wishId": "wish2",
    "content": "Work through Go tutorials and build a project.",
    "priority": 1,
    "due": "2024-06-01T00:00:00Z"
}

### Create a wish 3 for user1
POST {{baseUrl}}/wishes/user1
Content-Type: application/json

{
    "title": "Learn Rust",
    "wishId": "wish3",
    "content": "Work through Rust tutorials and build a project.",
    "priority": 3,
    "due": "2024-06-01T00:00:00Z"
}

### Create a wish for user2
POST {{baseUrl}}/wishes/user2
Content-Type: application/json

{
    "title": "Learn JavaScript",
    "wishId": "wish3",
    "content": "Work through JavaScript tutorials and build a project.",
    "priority": 1,
    "due": "2024-06-01T00:00:00Z"
}

### Update a wish for user1
PUT {{baseUrl}}/wishes/user1/wish1
Content-Type: application/json

{
    "title": "Learn Python - Updated",
    "content": "Work through Python tutorials and build a project. Updated content.",
    "priority": 5,
    "created": "2024-05-22T10:00:00Z",
    "due": "2024-06-01T00:00:00Z"
}

### Get all wishes for user1
GET {{baseUrl}}/wishes/user1

### Get all wishes for user2
GET {{baseUrl}}/wishes/user2

### Get a specific wish for user1
GET {{baseUrl}}/wishes/user1/wish1

### Get non-existent wish for user1
GET {{baseUrl}}/wishes/user1/wish999

### Get all wishes sorted by priortiy
GET {{baseUrl}}/wishes/all?sort_by=priority&order=asc

### Get all wishes sorted by created date
GET {{baseUrl}}/wishes/all?sort_by=created&order=desc

### Get all wishes sorted by due date
GET {{baseUrl}}/wishes/all?sort_by=due&order=asc

### Get wishes for user1 sorted by created date in ascending order
GET {{baseUrl}}/wishes/user1?sort_by=created&order=asc

### Get wishes for user1 sorted by priority in descending order
GET {{baseUrl}}/wishes/user1?sort_by=priority&order=desc

### Get wishes for user2 sorted by due date in ascending order
GET {{baseUrl}}/wishes/user2?sort_by=due&order=asc

### Delete a wish for user1
DELETE {{baseUrl}}/wishes/user1/wish1

### Delete a wish for user2
DELETE {{baseUrl}}/wishes/user2/wish3