#@baseUrl = http://localhost:8080
@baseUrl = http://ahorro-wishlist-savak-alb-1075899136.us-east-1.elb.amazonaws.com
### Info
GET {{baseUrl}}/info

### Health Check
GET {{baseUrl}}/health

### Create a new wish for user50
POST {{baseUrl}}/wishes/user50
Content-Type: application/json

{
    "title": "Learn Python",
    "wishId": "wish1",
    "content": "Work through Python tutorials and build a project.",
    "priority": 4,
    "due": "2024-06-01T00:00:00Z"
}

### Create another wish for user50
POST {{baseUrl}}/wishes/user50
Content-Type: application/json

{
    "title": "Learn Go",
    "wishId": "wish2",
    "content": "Work through Go tutorials and build a project.",
    "priority": 1,
    "due": "2024-06-01T00:00:00Z"
}

### Create a wish 3 for user50
POST {{baseUrl}}/wishes/user50
Content-Type: application/json

{
    "title": "Learn Rust",
    "wishId": "wish3",
    "content": "Work through Rust tutorials and build a project.",
    "priority": 3,
    "due": "2024-06-01T00:00:00Z"
}

### Create a wish for user51
POST {{baseUrl}}/wishes/user51
Content-Type: application/json

{
    "title": "Learn JavaScript",
    "wishId": "wish3",
    "content": "Work through JavaScript tutorials and build a project.",
    "priority": 1,
    "due": "2024-06-01T00:00:00Z"
}

### Update a wish for user50
PUT {{baseUrl}}/wishes/user50/wish1
Content-Type: application/json

{
    "title": "Learn Python - Updated",
    "content": "Work through Python tutorials and build a project. Updated content.",
    "priority": 5,
    "created": "2024-05-22T10:00:00Z",
    "due": "2024-06-01T00:00:00Z"
}

### Get all wishes for user1
GET {{baseUrl}}/wishes/user50

### Get all wishes for user2
GET {{baseUrl}}/wishes/user51

### Get a specific wish for user1
GET {{baseUrl}}/wishes/user50/wish1

### Get non-existent wish for user50
GET {{baseUrl}}/wishes/user50/wish999

### Get all wishes sorted by priortiy
GET {{baseUrl}}/wishes/all?sort_by=priority&order=asc

### Get all wishes sorted by created date
GET {{baseUrl}}/wishes/all?sort_by=created&order=desc

### Get all wishes sorted by due date
GET {{baseUrl}}/wishes/all?sort_by=due&order=asc

### Get all wishes paginated (page 1, size 5)
GET {{baseUrl}}/wishes/all?sort_by=due&order=desc&limit=5

### Get all wishes paginated (page 2, size 5)
GET {{baseUrl}}/wishes/all?sort_by=due&order=desc&limit=5&next_token=eyJkdWUiOnsiUyI6IjIwMjUtMDYtMjlUMTE6MTI6MzlaIn0sInVzZXJJZCI6eyJTIjoidXNlcjE2In0sIndpc2hJZCI6eyJTIjoid2lzaDEifSwiYWxsIjp7IlMiOiJhbGwifX0=

### Get wishes for user1 sorted by created date in ascending order
GET {{baseUrl}}/wishes/user1?sort_by=created&order=asc

### Get 5 first wishes for user1 sorted by created date in descending order
GET {{baseUrl}}/wishes/user1?sort_by=created&order=desc&limit=5

### Get wishes for user1 with pagination (page 2, size 5)
GET {{baseUrl}}/wishes/user1?sort_by=created&order=desc&limit=5&next_token=eyJ1c2VySWQiOnsiUyI6InVzZXIxIn0sIndpc2hJZCI6eyJTIjoid2lzaDUifSwiY3JlYXRlZCI6eyJTIjoiMjAyNS0wNS0zMVQxMToxMjozNFoifX0=

### Get wishes for user1 sorted by priority in descending order
GET {{baseUrl}}/wishes/user1?sort_by=priority&order=desc

### Get wishes for user2 sorted by due date in ascending order
GET {{baseUrl}}/wishes/user2?sort_by=due&order=asc

### Delete a wish for user1
DELETE {{baseUrl}}/wishes/user1/wish1

### Delete a wish for user2
DELETE {{baseUrl}}/wishes/user2/wish3